### ISSUE TITLE
Differences between Pontem's Move implementation and Outmove

### ISSUE THREAD

**Issue by nud3l** [pontem-network/pontem#125]
This is more of a question rather than an issue. I tried asking in the Telegram, but I guess because I included a link some bot automatically kicked me :man_shrugging: 

I was curious about the differences of Pontem's Move VM vs outmove (https://github.com/outmove/omv) are. In particular, I think by default Move restricts to who it can send funds to, i.e. addresses need to be generated which AFAIK is changed in outmove. But I'm not very deep into the differences so I'd thought I'd ask directly. Thanks!

**Comment by borispovod** [comment]
Hi @nud3l 

We are not so familiar with omv, so it's hard to compare for us. 

Pontem Move VM is a fork of Diem Move VM, but adopted for WASM Runtime used by Substrate and Polkadot/Kusama based chains.

> I think by default Move restricts to who it can send funds to

These restrictions are implemented not directly in Move VM, but in [standard library](https://docs.pontem.network/03.-move-vm/stdlib) used by Diem or Pontem. So if you don't want such restrictions, you can avoid them by changing standard library in your own fork, or by using [Treasury or Root signatures](https://docs.pontem.network/03.-move-vm/compiler_and_toolset#root-and-treasury-signers) in Pontem.
