### ISSUE TITLE
failed to run custom build command for `stdlib v0.1.0

### ISSUE THREAD

**Issue by POMbn** [pontem-network/pontem#133]
Hi,

We are getting this error when building the node:

error: failed to run custom build command for `stdlib v0.1.0 (https://github.com/pontem-network/sp-move-vm.git?rev=a6585179256bcb44c5e1db34201c3a5b6c8e3693#a6585179)`

Caused by:
  process didn't exit successfully: `/home/pontem/pontem/target/release/build/stdlib-eae87de3139b381b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  Cloning into 'move-stdlib'...
  Note: switching to '34cedad7436f7dad6c9a521f3f6199324737d69f'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:

    git switch -c <new-branch-name>

  Or undo this operation with:

    git switch -

  Turn off this advice by setting config variable advice.detachedHead to false

  HEAD is now at 34cedad Merge pull request #26 from pontem-network/feature-update-readme-pnt
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pontem/.cargo/git/checkouts/sp-move-vm-1e79a042c2a39ea0/a658517/stdlib/build.rs:26:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Seems like it can't unwrap the dependencie?

**Comment by cab404** [comment]
Do you have `move-tools` in your PATH?

**Comment by POMbn** [comment]
> Do you have `dove` in your PATH?

Where would i find this?
Is it a part of Debian or is it a rust thing?

**Comment by cab404** [comment]
> > Do you have `dove` in your PATH?
> 
> Where would i find this? Is it a part of Debian or is it a rust thing?

It's part of [move-tools](github.com/pontem-network/move-tools). Just install it and try building again.

**Comment by POMbn** [comment]
that fixed it.Thanks
