### ISSUE TITLE
Refactoring primitives/currencies

### ISSUE THREAD

**Issue by m1ome** [pontem-network/pontem#137]
### Task description
We need to refactor [currency.rs](https://github.com/pontem-network/pontem/blob/master/primitives/src/currency.rs).
Currently is quite annoying to add new one, with a lot of hand-crafted-work.

Best way to do it is to wrap it to a macro, in e.g. we can look how [Acala](https://github.com/AcalaNetwork/Acala/blob/master/primitives/src/currency.rs) implemented similar case (but if we adopt code we should clean up all EVM and other unnecessary stuff)

### Definition of done
- Adding new currency as simple as adding one line of code

**Comment by borispovod** [comment]
Please, ignore EVM related parts, we don't need them
